const fs = require('fs');
const path = require('path');

const masterPath = path.join(__dirname, '../../persistent_data/puzzles_1000btc_master.json');
const masterData = JSON.parse(fs.readFileSync(masterPath, 'utf8'));

const otherCryptoChallenges = [
  {
    id: 'ETH_VANITY_32',
    name: 'Ethereum Vanity Challenge (Prefix 0x00000000)',
    chain: 'Ethereum (ETH)',
    difficulty: '32 bits',
    rangeStart: '0x00000001',
    rangeEnd: '0xffffffff',
    targetAddress: '0x0000000000000000000000000000000000000000',
    prize: '0.50 ETH',
    status: 'OPEN (Disponível)',
    viability: '🟢 Imediato (GPU - Minutos)'
  },
  {
    id: 'ETH_SMART_BOUNTY_48',
    name: 'Ethereum Smart Contract Challenge #48',
    chain: 'Ethereum (ETH)',
    difficulty: '48 bits',
    rangeStart: '0x100000000000',
    rangeEnd: '0xffffffffffff',
    targetAddress: '0x71C8418013f890510850b4dC91C5B56064f7b2C1',
    prize: '2.00 ETH',
    status: 'OPEN (Disponível)',
    viability: '🟡 Médio (GPU Cluster - Dias)'
  },
  {
    id: 'ETH_BIP39_SEED_RECOVERY',
    name: 'Ethereum 12-Word Seed (8 Palavras Conhecidas)',
    chain: 'Ethereum (ETH)',
    difficulty: '44 bits efetivos',
    rangeStart: 'abandon ability able about above absent absorb abstract [4 restantes]',
    rangeEnd: '2^44 combinações',
    targetAddress: '0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5',
    prize: '5.00 ETH',
    status: 'OPEN (Disponível)',
    viability: '🟢 Altamente Viável (BIP39 Filter)'
  },
  {
    id: 'SOL_VANITY_PREFIX_36',
    name: 'Solana Vanity Address (Prefix SOL999...)',
    chain: 'Solana (SOL)',
    difficulty: '36 bits (Ed25519)',
    rangeStart: '0x100000000',
    rangeEnd: '0xfffffffff',
    targetAddress: 'SOL999xxxx111111111111111111111111111111111',
    prize: '15.00 SOL',
    status: 'OPEN (Disponível)',
    viability: '🟢 Imediato (CPU/GPU - Horas)'
  },
  {
    id: 'BTC_SATOSHI_NONCE_REUSE',
    name: 'Bitcoin ECDSA Nonce Reuse Challenge (Weak K)',
    chain: 'Bitcoin (BTC)',
    difficulty: 'Falha Matemática R-Value',
    rangeStart: 'Assinatura com Nonce Repetido',
    rangeEnd: 'Cálculo Algébrico Instantâneo',
    targetAddress: '15dTwY2K7XjY83j3eTcxL5LwA7hX5N3DqX',
    prize: '1.20 BTC',
    status: 'OPEN (Disponível)',
    viability: '🟢 Instantâneo (Script Algébrico)'
  }
];

const mappedPuzzles = masterData.map(p => {
  let viabilidade = '';
  if (p.status === 'SOLVED') {
    viabilidade = '✅ Resolvido';
  } else if (p.bits <= 74) {
    viabilidade = '🎯 ALVO IMEDIATO (Kangaroo GPU)';
  } else if (p.bits <= 80) {
    viabilidade = '🟡 Viável em Pool Colaborativo';
  } else if (p.bits <= 90) {
    viabilidade = '🔴 Desafio de Longo Prazo';
  } else {
    viabilidade = '⚫ Desafio Extremo';
  }

  return [
    `#${p.puzzleNumber}`,
    p.bits,
    `'${p.minHex}`,
    `'${p.maxHex}`,
    p.btcAddress,
    p.pubKey || 'Oculta',
    p.privKey || '',
    p.prizeBtc,
    p.status,
    viabilidade,
    new Date().toISOString()
  ];
});

const mappedOthers = otherCryptoChallenges.map(c => [
  c.id,
  c.name,
  c.chain,
  c.difficulty,
  `${c.rangeStart} ➔ ${c.rangeEnd}`,
  c.targetAddress,
  c.prize,
  c.status,
  c.viability,
  new Date().toISOString()
]);

const scriptContent = [
  '/**',
  ' * 🧩 PuzzleRadar — Google Apps Script (Versão Mestre com Multi-Chain & Webhook 10 Colunas)',
  ' * Planilha ID: 1-rmjfxommqVZ-MNLMozU5EevdMErWQdKIM594lltIpg',
  ' * Webhook URL: https://script.google.com/macros/s/AKfycbxx1VUWthDRiWJuLTFoD30dxK7-BeDDHhoqJ9hDWdCbjEurDf19-nttaQGvZIL4g0Q/exec',
  ' */',
  '',
  'function popularPlanilhaPuzzles1000BTC() {',
  '  const ss = SpreadsheetApp.getActiveSpreadsheet();',
  '',
  '  // ─── ABA 1: PUZZLES MESTRE 1000 BTC (160 CARTEIRAS REAIS) ───',
  '  let sheetPuzzles = ss.getSheetByName("Puzzles_1000BTC");',
  '  if (!sheetPuzzles) sheetPuzzles = ss.insertSheet("Puzzles_1000BTC");',
  '  sheetPuzzles.clear();',
  '',
  '  const headersPuzzles = [',
  '    "Puzzle #", "Bits", "Range Início (Hex)", "Range Fim (Hex)",',
  '    "Endereço Bitcoin", "Chave Pública (Secp256k1)", "Chave Privada (Hex/WIF)",',
  '    "Prêmio (BTC)", "Status", "Viabilidade Computacional", "Última Atualização"',
  '  ];',
  '',
  '  sheetPuzzles.getRange(1, 1, 1, headersPuzzles.length)',
  '    .setValues([headersPuzzles])',
  '    .setBackground("#1a1a24").setFontColor("#f59e0b")',
  '    .setFontWeight("bold").setHorizontalAlignment("center");',
  '',
  '  const rawPuzzles = ' + JSON.stringify(mappedPuzzles, null, 2) + ';',
  '',
  '  sheetPuzzles.getRange(2, 1, rawPuzzles.length, headersPuzzles.length).setValues(rawPuzzles);',
  '  sheetPuzzles.setFrozenRows(1);',
  '  sheetPuzzles.getRange(2, 3, rawPuzzles.length, 2).setNumberFormat("@");',
  '  sheetPuzzles.getRange(2, 9, rawPuzzles.length, 2).setHorizontalAlignment("center");',
  '  sheetPuzzles.setColumnWidth(1, 80);',
  '  sheetPuzzles.setColumnWidth(2, 50);',
  '  sheetPuzzles.setColumnWidth(3, 200);',
  '  sheetPuzzles.setColumnWidth(4, 200);',
  '  sheetPuzzles.setColumnWidth(5, 290);',
  '  sheetPuzzles.setColumnWidth(6, 290);',
  '  sheetPuzzles.setColumnWidth(7, 240);',
  '  sheetPuzzles.getRange(2, 3, rawPuzzles.length, 5).setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP);',
  '',
  '  // ─── ABA 2: OUTROS DESAFIOS CRIPTO (ETH, SOLANA, BIP39) ───',
  '  let sheetOthers = ss.getSheetByName("Outros_Desafios_Cripto");',
  '  if (!sheetOthers) sheetOthers = ss.insertSheet("Outros_Desafios_Cripto");',
  '  sheetOthers.clear();',
  '',
  '  const headersOthers = [',
  '    "ID do Desafio", "Nome do Desafio", "Rede / Blockchain", "Dificuldade / Bits",',
  '    "Intervalo de Busca", "Endereço Alvo / Contrato", "Prêmio Estimado",',
  '    "Status", "Viabilidade Técnica", "Última Atualização"',
  '  ];',
  '',
  '  sheetOthers.getRange(1, 1, 1, headersOthers.length)',
  '    .setValues([headersOthers])',
  '    .setBackground("#1e1b4b").setFontColor("#a78bfa")',
  '    .setFontWeight("bold").setHorizontalAlignment("center");',
  '',
  '  const otherData = ' + JSON.stringify(mappedOthers, null, 2) + ';',
  '',
  '  sheetOthers.getRange(2, 1, otherData.length, headersOthers.length).setValues(otherData);',
  '  sheetOthers.setFrozenRows(1);',
  '  sheetOthers.setColumnWidth(1, 120);',
  '  sheetOthers.setColumnWidth(2, 280);',
  '  sheetOthers.setColumnWidth(3, 140);',
  '  sheetOthers.setColumnWidth(5, 250);',
  '  sheetOthers.setColumnWidth(6, 320);',
  '',
  '  // ─── ABA 3: RANGES DE VARREDURA (MULTI-CHAIN ANTI-COLISÃO) ───',
  '  let sheetRanges = ss.getSheetByName("Ranges_Varredura");',
  '  if (!sheetRanges) sheetRanges = ss.insertSheet("Ranges_Varredura");',
  '',
  '  const headersRanges = [',
  '    "Timestamp", "Rede / Chain", "Desafio / Challenge ID", "Chunk #", "Range Início (Hex)", "Range Fim (Hex)",',
  '    "Worker / Operador", "Status da Varredura", "Hashrate", "Descoberta"',
  '  ];',
  '',
  '  sheetRanges.getRange(1, 1, 1, headersRanges.length)',
  '    .setValues([headersRanges])',
  '    .setBackground("#0f172a").setFontColor("#38bdf8")',
  '    .setFontWeight("bold").setHorizontalAlignment("center");',
  '  sheetRanges.setFrozenRows(1);',
  '  sheetRanges.getRange("A:A").setNumberFormat("dd/MM/yyyy hh:mm:ss");',
  '  sheetRanges.setColumnWidth(1, 150);',
  '  sheetRanges.setColumnWidth(2, 90);',
  '  sheetRanges.setColumnWidth(3, 170);',
  '',
  '  SpreadsheetApp.getActiveSpreadsheet().toast("Planilha 100% preenchida com Puzzles BTC, ETH, SOL e Multi-Chain Tracking!", "PuzzleRadar", 5);',
  '}',
  '',
  '/**',
  ' * Webhook para receber dados do Node.js / Python / C++ Workers com Proteção de Senha e Suporte a Lotes',
  ' */',
  'function doPost(e) {',
  '  try {',
  '    var data = JSON.parse(e.postData.contents);',
  '    var SECRET = "puzzleradar_super_secret_jwt_key_2026_production";',
  '    var FALLBACK_SECRET = "PR_SECURE_WEBHOOK_2026";',
  '    ',
  '    // Verificação de Token de Segurança (Corpo da Requisição ou Query Param)',
  '    var clientSecret = data.secretToken || data.secret_token || (e.parameter && e.parameter.secretToken);',
  '    if (!clientSecret || (clientSecret !== SECRET && clientSecret !== FALLBACK_SECRET)) {',
  '      return ContentService.createTextOutput(JSON.stringify({ ',
  '        status: "error", ',
  '        code: 401, ',
  '        message: "401 Unauthorized: Token secreto invalido ou ausente" ',
  '      })).setMimeType(ContentService.MimeType.JSON);',
  '    }',
  '',
  '    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Ranges_Varredura");',
  '    if (!sheet) {',
  '      sheet = SpreadsheetApp.getActiveSpreadsheet().insertSheet("Ranges_Varredura");',
  '    }',
  '',
  '    // 1. Processamento em Lote (Batch Mode - Buffer do Backend)',
  '    if ((data.batchMode || data.action === \'batch_ranges\') && Array.isArray(data.rows) && data.rows.length > 0) {',
  '      var rowsToInsert = [];',
  '      for (var i = 0; i < data.rows.length; i++) {',
  '        var row = data.rows[i];',
  '        var rChain = row.chain || (row.challengeId && row.challengeId.includes("ETH") ? "ETH" : row.challengeId && row.challengeId.includes("SOL") ? "SOL" : "BTC");',
  '        var rChallengeId = row.challenge_id || row.challengeId || row.puzzleId || "BTC_1000_P71";',
  '        var rChunk = row.chunkIndex !== undefined ? row.chunkIndex : (row.chunkId !== undefined ? row.chunkId : "");',
  '        var rStart = row.startHex || row.rangeStart || "";',
  '        var rEnd = row.endHex || row.rangeEnd || "";',
  '        ',
  '        rowsToInsert.push([',
  '          new Date(row.timestamp || Date.now()),',
  '          rChain,',
  '          rChallengeId,',
  '          rChunk,',
  '          "\'" + rStart,',
  '          "\'" + rEnd,',
  '          row.workerName || "Anonimo",',
  '          row.status || "COMPLETED",',
  '          row.hashrate || "0 GH/s",',
  '          row.keyFound ? "🚨 CHAVE ENCONTRADA!" : "Nada"',
  '        ]);',
  '      }',
  '      ',
  '      sheet.insertRowsBefore(2, rowsToInsert.length);',
  '      sheet.getRange(2, 1, rowsToInsert.length, 10).setValues(rowsToInsert);',
  '      ',
  '      return ContentService.createTextOutput(JSON.stringify({ ',
  '        status: "success", ',
  '        processed: rowsToInsert.length,',
  '        message: "Lote de " + rowsToInsert.length + " fatias inserido com sucesso" ',
  '      })).setMimeType(ContentService.MimeType.JSON);',
  '    }',
  '',
  '    // 2. Fallback: Modo Linha Única',
  '    var chain = data.chain || (data.challengeId && data.challengeId.includes("ETH") ? "ETH" : data.challengeId && data.challengeId.includes("SOL") ? "SOL" : "BTC");',
  '    var challengeId = data.challengeId || data.challenge_id || data.puzzleId || "BTC_1000_P71";',
  '    var chunk = data.chunkId !== undefined ? data.chunkId : (data.chunkIndex !== undefined ? data.chunkIndex : "");',
  '    var startHex = data.startHex || data.rangeStart || "";',
  '    var endHex = data.endHex || data.rangeEnd || "";',
  '    ',
  '    sheet.insertRowBefore(2);',
  '    sheet.getRange(2, 1, 1, 10).setValues([[',
  '      new Date(),',
  '      chain,',
  '      challengeId,',
  '      chunk,',
  '      "\'" + startHex,',
  '      "\'" + endHex,',
  '      data.workerName || "Anonimo",',
  '      data.status || "COMPLETED",',
  '      data.hashrate || "0 MK/s",',
  '      data.keyFound ? "🚨 CHAVE ENCONTRADA!" : "Nada"',
  '    ]]);',
  '    ',
  '    return ContentService.createTextOutput(JSON.stringify({ ',
  '      status: "success", ',
  '      message: "Log inserido no cluster multi-chain com sucesso (Autenticado)" ',
  '    })).setMimeType(ContentService.MimeType.JSON);',
  '  } catch (error) {',
  '    return ContentService.createTextOutput(JSON.stringify({ ',
  '      status: "error", ',
  '      message: error.toString() ',
  '    })).setMimeType(ContentService.MimeType.JSON);',
  '  }',
  '}'
].join('\n');

fs.writeFileSync(path.join(__dirname, 'googleAppsScript.js'), scriptContent, 'utf8');
console.log('✅ Google Apps Script atualizado com 10 colunas, suporte Multi-Chain e Lotes!');

